#!/bin/bash

cd /home/ec2-user

# Install python3
#yum -y install python3-3.7.9-1.amzn2.0.2
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update -y
sudo apt install python3.8
python --version

# Install pip
#yum -y install python3-pip-9.0.3
#pip3 ipip3 --versionnstall -Iv --upgrade pip==20.2.1
sudo apt install python3-pip
pip3 --version

# Install awscli and python dev libraries
pip install --user -r scripts/requirements.txt
